### ISSUE TITLE
Aerial v6.1 won't start nor Preview

### ISSUE THREAD

**Issue by jbattermann** [cDima/Aerial#149]
Just did a fresh Win10 installation (v1709 Build 16299.19) and installed v6.1 of the Aerial Screensaver but for some reason.. it doesn't run at all with this fresh install.

Eventviewer entry says the following:

```
Application: Aerial.scr
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(System.Guid ByRef, System.Object, Int32, System.Guid ByRef)
   at System.Windows.Forms.AxHost.CreateWithLicense(System.String, System.Guid)
   at System.Windows.Forms.AxHost.CreateInstanceCore(System.Guid)
   at System.Windows.Forms.AxHost.CreateInstance()
   at System.Windows.Forms.AxHost.GetOcxCreate()
   at System.Windows.Forms.AxHost.TransitionUpTo(Int32)
   at System.Windows.Forms.AxHost.CreateHandle()
   at System.Windows.Forms.Control.CreateControl(Boolean)
   at System.Windows.Forms.Control.CreateControl(Boolean)
   at System.Windows.Forms.AxHost.EndInit()
   at ScreenSaver.ScreenSaverForm.InitializeComponent()
   at ScreenSaver.ScreenSaverForm..ctor()
   at ScreenSaver.ScreenSaverForm..ctor(IntPtr)
   at ScreenSaver.Program.Main(System.String[])
```

Is there anything that might be missing on my system or what might be going on here?

Thanks,
-J

**Comment by hoytler** [comment]
Try going to Add Features -> Add option features -> And adding Windows Media Player. It seems that this ScreenSaver has a dependency on WMP.

**Comment by jbattermann** [comment]
Ahhh.. that makes sense - I got a 'N' version of Windows 10 (European one without WMP by default installation).. will try it and report back if that helped. Thanks!

**Comment by cDima** [comment]
Thanks, I'll try to wrap this up as a better exception with a link to a
readme.

**Comment by jbattermann** [comment]
Unfortunately that was not it.. or not completely. Installed the Windows Media Player Feature, rebooted.. but still getting the exact same aforementioned exception.

Is there any other dependency the screensaver has that might be missing?

**Comment by jbattermann** [comment]
Ah alright - as it turns out merely adding the 'Windows Media Player Feature' in Windows 10 itself is not enough for Windows N and KN versions - you need to get the appropriate '[Media Feature Pack for N edition of Windows 10](https://www.microsoft.com/en-us/software-download/mediafeaturepack)' corresponding to your version of Windows 10 (RTM, Creator's Update, etc).

This will install the missing ActiveX components and then it works!

**Comment by JeremyNGalloway** [comment]
@hoytler Re-enabling WMP fixed my issue on Win10. No restart needed. ty.

**Comment by jminternelia** [comment]
I am having this issue now. Non-N/KN. 10.0.17134 

Windows Media Player is installed.
