### ISSUE TITLE
Screensaver Producing Fault -- No Longer WOrking

### ISSUE THREAD

**Issue by grok** [cDima/Aerial#179]
```
Faulting application name: Aerial.scr, version: 1.0.0.0, time stamp: 0x58968453
Faulting module name: KERNELBASE.dll, version: 10.0.17134.319, time stamp: 0x1e206b26
Exception code: 0xe0434352
Fault offset: 0x000000000003a388
Faulting process id: 0xc74
Faulting application start time: 0x01d475fc2b3e5b09
Faulting application path: C:\Windows\Aerial.scr
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 60cd5670-e716-4e22-9767-1387c6e5dfca
Faulting package full name: 
Faulting package-relative application ID: 
```

This happens any time I try to play the screensaver -- regardless of settings or if I run it as administrator or a normal user.

**Comment by grok** [comment]
```
Fault bucket 2122483428348416191, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Aerial.exe
P2: 1.0.0.0
P3: 58968453
P4: System.Windows.Forms
P5: 4.7.3221.0
P6: 5b885a5a
P7: 66e
P8: 36
P9: PSZQOADHX1U5ZAHBHOHGHLDGIY4QIXHX
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2DB5.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2EBF.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2EE0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2EEF.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2F2F.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Aerial.exe_e5de7d531f34e9ccfb2caaf653e9c077e4b03ba1_bd55b00d_12a232b6

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0b5bde10-df5c-4c51-a734-66dd1e65c149
Report Status: 268435456
Hashed bucket: 04f2efa41eff6f721d74936ec45c50bf
Cab Guid: 0
```

**Comment by grok** [comment]
```
Version=1
EventType=CLR20r3
EventTime=131860025033751745
ReportType=2
Consent=1
UploadTime=131860025037781542
ReportStatus=268435456
ReportIdentifier=99846f18-35af-4a19-9642-1c50b454c688
IntegratorReportIdentifier=9e860e32-6633-4eb7-8b8a-8ff290c41632
Wow64Host=34404
NsAppName=Aerial.exe
OriginalFilename=Aerial.exe
AppSessionGuid=00001744-0001-001e-7560-f97ffe75d401
TargetAppId=W:000675703215f50c2c8ab430f3d4514227a300000000!000070aacb6465aab9eb7d7a5967015cc255d52b188a!Aerial.exe
TargetAppVer=2017//02//05:01:48:03!0!Aerial.exe
BootId=4294967295
TargetAsId=5772
IsFatal=1
Response.BucketId=04f2efa41eff6f721d74936ec45c50bf
Response.BucketTable=5
Response.LegacyBucketId=2122483428348416191
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=Aerial.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=1.0.0.0
Sig[2].Name=Problem Signature 03
Sig[2].Value=58968453
Sig[3].Name=Problem Signature 04
Sig[3].Value=System.Windows.Forms
Sig[4].Name=Problem Signature 05
Sig[4].Value=4.7.3221.0
Sig[5].Name=Problem Signature 06
Sig[5].Value=5b885a5a
Sig[6].Name=Problem Signature 07
Sig[6].Value=66e
Sig[7].Name=Problem Signature 08
Sig[7].Value=36
Sig[8].Name=Problem Signature 09
Sig[8].Value=PSZQOADHX1U5ZAHBHOHGHLDGIY4QIXHX
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.17134.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=5f08
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=5f0805ce60882a26d86e574723acd45d
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=4dec
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=4dec18d20cdb7d5a68454623c1c90974
UI[2]=C:\Users\Sterling Hamilton\Downloads\Aerial.exe
LoadedModule[0]=C:\Users\Sterling Hamilton\Downloads\Aerial.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\System32\KERNEL32.dll
LoadedModule[4]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\SYSTEM32\apphelp.dll
LoadedModule[6]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[7]=C:\Windows\System32\msvcrt.dll
LoadedModule[8]=C:\Windows\System32\sechost.dll
LoadedModule[9]=C:\Windows\System32\RPCRT4.dll
LoadedModule[10]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[11]=C:\Windows\System32\SHLWAPI.dll
LoadedModule[12]=C:\Windows\System32\combase.dll
LoadedModule[13]=C:\Windows\System32\ucrtbase.dll
LoadedModule[14]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[15]=C:\Windows\System32\GDI32.dll
LoadedModule[16]=C:\Windows\System32\gdi32full.dll
LoadedModule[17]=C:\Windows\System32\msvcp_win.dll
LoadedModule[18]=C:\Windows\System32\USER32.dll
LoadedModule[19]=C:\Windows\System32\win32u.dll
LoadedModule[20]=C:\Windows\System32\IMM32.DLL
LoadedModule[21]=C:\Windows\System32\kernel.appcore.dll
LoadedModule[22]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[23]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[24]=C:\Windows\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[25]=C:\Windows\assembly\NativeImages_v4.0.30319_64\mscorlib\a6021ef6892ab519b334a17992542017\mscorlib.ni.dll
LoadedModule[26]=C:\Windows\System32\ole32.dll
LoadedModule[27]=C:\Windows\system32\uxtheme.dll
LoadedModule[28]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[29]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System\8ff4bf965a60a85a0598226bf67e993a\System.ni.dll
LoadedModule[30]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Drawing\d56a87ba57efe8f63335298ab1cb8772\System.Drawing.ni.dll
LoadedModule[31]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\a8f8eef9e281ad0ac06dc269147ae72c\System.Windows.Forms.ni.dll
LoadedModule[32]=C:\Windows\System32\shell32.dll
LoadedModule[33]=C:\Windows\System32\cfgmgr32.dll
LoadedModule[34]=C:\Windows\System32\shcore.dll
LoadedModule[35]=C:\Windows\System32\windows.storage.dll
LoadedModule[36]=C:\Windows\System32\profapi.dll
LoadedModule[37]=C:\Windows\System32\powrprof.dll
LoadedModule[38]=C:\Windows\System32\FLTLIB.DLL
LoadedModule[39]=C:\Windows\System32\psapi.dll
LoadedModule[40]=C:\Windows\SYSTEM32\wldp.dll
LoadedModule[41]=C:\Windows\System32\CRYPT32.dll
LoadedModule[42]=C:\Windows\System32\MSASN1.dll
LoadedModule[43]=C:\Windows\System32\WINTRUST.dll
LoadedModule[44]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Core\4db19b6c7622a8939b4a5629cf59c5ff\System.Core.ni.dll
LoadedModule[45]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Configuration\ed57871eb5218c20f36290299e011a90\System.Configuration.ni.dll
LoadedModule[46]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xml\96b052a0815a6699986712bec8659f0f\System.Xml.ni.dll
LoadedModule[47]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[48]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[49]=C:\Windows\system32\rsaenh.dll
LoadedModule[50]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[51]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.17134.376_none_f9552fd530932a6f\comctl32.dll
LoadedModule[52]=C:\Windows\system32\dwmapi.dll
LoadedModule[53]=C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.17134.376_none_2c2e8d1c8af6f770\gdiplus.dll
LoadedModule[54]=C:\Windows\SYSTEM32\DWrite.dll
LoadedModule[55]=C:\Windows\System32\MSCTF.dll
LoadedModule[56]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[57]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.376_none_fb439a3730647da2\comctl32.dll
LoadedModule[58]=C:\Windows\System32\clbcatq.dll
LoadedModule[59]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=17134
OsInfo[3].Key=ubr
OsInfo[3].Value=376
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=37381
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.345.17134.0-11.0.90
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=16256
OsInfo[19].Key=svolsz
OsInfo[19].Value=940
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=180410
OsInfo[22].Key=bldtm
OsInfo[22].Value=1804
OsInfo[23].Key=bldbrch
OsInfo[23].Value=rs4_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.17134.376.amd64fre.rs4_release.180410-1804
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=ScreenSaver
AppPath=C:\Users\Sterling Hamilton\Downloads\Aerial.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=BC0E2334BE9B85935012509F5F37A385
MetadataHash=-166713565
```

**Comment by grok** [comment]
```
Application: Aerial.scr
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(System.Guid ByRef, System.Object, Int32, System.Guid ByRef)
   at System.Windows.Forms.AxHost.CreateWithLicense(System.String, System.Guid)
   at System.Windows.Forms.AxHost.CreateInstanceCore(System.Guid)
   at System.Windows.Forms.AxHost.CreateInstance()
   at System.Windows.Forms.AxHost.GetOcxCreate()
   at System.Windows.Forms.AxHost.TransitionUpTo(Int32)
   at System.Windows.Forms.AxHost.CreateHandle()
   at System.Windows.Forms.Control.CreateControl(Boolean)
   at System.Windows.Forms.Control.CreateControl(Boolean)
   at System.Windows.Forms.AxHost.EndInit()
   at ScreenSaver.ScreenSaverForm.InitializeComponent()
   at ScreenSaver.ScreenSaverForm..ctor()
   at ScreenSaver.ScreenSaverForm..ctor(IntPtr)
   at ScreenSaver.Program.Main(System.String[])
```

**Comment by grok** [comment]
Ok, I'm just going to disable it for the moment :( I really like this so I am hoping I can get it to work later.

Here's what I have done:

1. I have tried both the EXE and SCR files.
2. I have tried rebooting.
3. I have tried uninstall the screensaver itself and re-installing it within the Windows directory.
4. I have tried using a combination of Run as Administrator
5. I have looked at the event log and posted results above.
![image](https://user-images.githubusercontent.com/495761/48086471-cf689a00-e1b1-11e8-8a83-91bece2d6f2f.png)
6. I have tried going back 3 major versions -- they all do the same things.

Here's high level system info:

![image](https://user-images.githubusercontent.com/495761/48086670-400fb680-e1b2-11e8-96b2-0e018b89cf35.png)

**Comment by ventsislav-georgiev** [comment]
I have the same issue.

**Comment by juanchohq** [comment]
in my case this happend when the default video adapter is set to NVidia, setting to the Intel solve the problem...

**Comment by grok** [comment]
@juanchohq that's an interesting insight.

In my case, I have one Intel(R) UHD Graphics 615 -- no NVIDA software wrapper as of right now.

**Comment by briannosaurus** [comment]
I had this issue too, where it worked correctly on one up to date windows 10 and didn't on another almost same system. (both were built from master because 6.1 didn't work on either). Debugging i found aerialurl was always empty on https://github.com/cDima/Aerial/blob/master/ScreenSaver/AerialEntities.cs#L64 . It looks like it is trying to read the registry. Both systems had the same registry but for some reason i haven't figured out it just wouln't read the registry. so for a quick fix i added the lines

            if (string.IsNullOrEmpty(aerialUrl))
            {
                aerialUrl = "http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json";
            }

below: var aerialUrl = settings.JsonURL; to make it work

**Comment by ZarekParker** [comment]
I had this issue on Windows 10 1903 trying to run the linked 4k version in the readme.
To get the EXE to run without rebuilding the code, I fixed it by running regedit.exe, navigating to Computer\HKEY_CURRENT_USER\Software\ and then deleting the "AerialScreenSaver" folder.

Clearing the JsonURL key's value in the folder did not work.  Deleting the JsonURL key altogether did not work.

The settings are restored / regenerated after you click "OK" on the settings dialog.

**Comment by grok** [comment]
Closing since it's old as dirt.
