### ISSUE TITLE
4K Won't Launch

### ISSUE THREAD

**Issue by 3dp** [cDima/Aerial#185]
`Fault bucket 2109586355014758616, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Aerial.scr
P2: 6.2.0.0
P3: 59fbb050
P4: mscorlib
P5: 4.7.3221.0
P6: 5b8858d1
P7: 191a
P8: 1a
P9: System.ArgumentNullException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER96D4.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER97CF.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER97EF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER97F5.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9825.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Aerial.scr_2ff8444d319fb8e8fc5988697629f95ccefb6b5d_c7d09fc5_66b29db9

Analysis symbol: 
Rechecking for solution: 0
Report Id: c77d3ab4-bf55-4d33-8edf-dc0e1b9be26b
Report Status: 268435456
Hashed bucket: 221d476fde3892d58d46c19ce1aa70d8
`
`Application: Aerial.scr
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.IO.Path.Combine(System.String, System.String)
   at Aerial.Caching.IsHit(System.String)
   at Aerial.AerialContext.GetAllEntries()
   at Aerial.AerialContext.GetAllMovies()
   at ScreenSaver.SettingsForm.PopulateChosenVideoGroup()
   at ScreenSaver.SettingsForm.LoadSettings()
   at ScreenSaver.SettingsForm..ctor()
   at Aerial.Program.Main(System.String[])

`

`Faulting application name: Aerial.scr, version: 6.2.0.0, time stamp: 0x59fbb050
Faulting module name: KERNELBASE.dll, version: 10.0.17134.407, time stamp: 0xade8d4fe
Exception code: 0xe0434352
Fault offset: 0x00111812
Faulting process id: 0x6248
Faulting application start time: 0x01d49b000358f25a
Faulting application path: C:\WINDOWS\Aerial.scr
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7d835885-20ba-40a4-8d81-f04d712406e1
Faulting package full name: 
Faulting package-relative application ID: `

On a Dell with an NVidia, except the Intel graphics are running...

**Comment by ikjadoon** [comment]
Having the same issue. :(

**Comment by ignusfast** [comment]
Same issue here...  I'm hoping this screensaver isn't dead, since it's my favorite.
